version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src"
    schedule:
      interval: daily
    open-pull-requests-limit: 50
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
